### 
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "Xabier",
    "surname": "Breixo",
    "phone": "662146921",
    "email": "xabier@inventing.com"

}

###

GET http://localhost:9000/api/users HTTP/1.1
###

GET http://localhost:9000/api/users/619dfcd3c2f843afc0d4ecb6 HTTP/1.1

### 
PUT http://localhost:9000/api/users/619dfcd3c2f843afc0d4ecb6 HTTP/1.1
Content-Type: application/json

{
    "name": "Amancio",
    "surname": "Ortiga",
    "phone": "685471236",
    "email": "amanciortiga@indietext.com"

}

###
DELETE http://localhost:9000/api/users/619dfcd3c2f843afc0d4ecb6 HTTP/1.1

